version: '3.8'

services:

  redis:
   container_name: redis
   image: redis:latest
   restart: unless-stopped

  canvas_api:
   container_name: canvas_api
   image: canvas_api:latest
   restart: unless-stopped
   environment:
     - CONFIGURATION_ENV=config.DockerConfig
   build:
     context: .
     dockerfile: Dockerfile
   entrypoint: ['python', 'app.py']

   ports:
     - '1337:1337'
   depends_on:
     - redis
